"use client";

import { useEffect, useRef, useState } from "react";
import { useChatStore } from "@/lib/chat-store";
import Sidebar from "./Sidebar";
import WelcomeScreen from "./WelcomeScreen";
import MessageThread from "./MessageThread";
import InputBar from "./InputBar";
import OnboardingTour from "./OnboardingTour";
import { getModel } from "@/lib/models";
import Image from "next/image";
import {
  Share2, MoreHorizontal, Menu,
  Copy, Download, Check, Pencil, Trash2, HelpCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";

function conversationToMarkdown(title: string, messages: { role: string; content: string }[]): string {
  const out: string[] = [`# ${title}`, ""];
  for (const m of messages) {
    out.push(m.role === "user" ? "### You" : "### DMOOP");
    out.push("");
    out.push(m.content);
    out.push("");
  }
  out.push("---");
  out.push(`Generated by DMOOP · ${new Date().toLocaleString()}`);
  return out.join("\n");
}

export default function ChatLayout() {
  const conv = useChatStore((s) => s.activeConversation());
  const selectedModel = useChatStore((s) => s.selectedModel);
  const deleteConversation = useChatStore((s) => s.deleteConversation);
  const renameConversation = useChatStore((s) => s.renameConversation);
  const current = getModel(selectedModel);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [moreOpen, setMoreOpen] = useState(false);
  const [copiedShare, setCopiedShare] = useState(false);
  const [renaming, setRenaming] = useState(false);
  const [renameValue, setRenameValue] = useState("");
  const shareRef = useRef<HTMLDivElement>(null);
  const moreRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (shareRef.current && !shareRef.current.contains(e.target as Node)) setShareOpen(false);
      if (moreRef.current && !moreRef.current.contains(e.target as Node)) setMoreOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const hasConv = !!conv && conv.messages.length > 0;

  const copyAsMarkdown = async () => {
    if (!conv) return;
    const md = conversationToMarkdown(conv.title, conv.messages);
    await navigator.clipboard.writeText(md);
    setCopiedShare(true);
    setTimeout(() => setCopiedShare(false), 1500);
  };

  const downloadAsMarkdown = () => {
    if (!conv) return;
    const md = conversationToMarkdown(conv.title, conv.messages);
    const safeTitle = conv.title.replace(/[^a-z0-9-_]+/gi, "-").slice(0, 50);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dmoop-${safeTitle}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShareOpen(false);
  };

  const nativeShare = async () => {
    if (!conv) return;
    const md = conversationToMarkdown(conv.title, conv.messages);
    if (navigator.share) {
      try {
        await navigator.share({
          title: `DMOOP — ${conv.title}`,
          text: md.slice(0, 4000),
        });
      } catch {}
    } else {
      await copyAsMarkdown();
    }
    setShareOpen(false);
  };

  const startRename = () => {
    if (!conv) return;
    setRenameValue(conv.title);
    setRenaming(true);
    setMoreOpen(false);
  };

  const commitRename = () => {
    if (conv && renameValue.trim()) {
      renameConversation(conv.id, renameValue.trim().slice(0, 100));
    }
    setRenaming(false);
  };

  const deleteCurrent = () => {
    if (!conv) return;
    if (!confirm("Delete this conversation? This can't be undone.")) return;
    deleteConversation(conv.id);
    setMoreOpen(false);
  };

  const showTour = () => {
    localStorage.removeItem("dmoop_onboarded_v1");
    window.location.reload();
  };

  return (
    <div className="flex h-screen overflow-hidden bg-[var(--dmoop-bg-app)]">
      <OnboardingTour />
      <Sidebar mobileOpen={mobileNavOpen} onMobileClose={() => setMobileNavOpen(false)} />

      <main className="flex-1 flex flex-col min-w-0 min-h-0 relative">
        <div
          className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] pointer-events-none opacity-40"
          style={{
            background: "radial-gradient(ellipse at top, rgba(193, 74, 42, 0.08) 0%, transparent 70%)",
          }}
        />

        {/* Top bar */}
        <header
          className="h-14 flex items-center justify-between px-4 sm:px-6 shrink-0 relative z-20 gap-2"
          style={{
            background: "rgba(250, 248, 245, 0.85)",
            backdropFilter: "blur(12px)",
            borderBottom: "1px solid var(--dmoop-border-soft)",
          }}
        >
          <div className="flex items-center gap-2 min-w-0 flex-1">
            <button
              onClick={() => setMobileNavOpen(true)}
              className="md:hidden p-2 -ml-2 rounded-lg text-[var(--dmoop-text-secondary)] hover:bg-white hover:shadow-[var(--dmoop-shadow-sm)] active:scale-95 transition-all"
              title="Open menu"
            >
              <Menu size={17} />
            </button>
            <div className="flex items-center gap-2 min-w-0">
              <span className="inline-flex items-center justify-center w-5 h-5 rounded bg-white border border-[var(--dmoop-border-soft)] p-0.5 shrink-0">
                <Image src="/dmoop-logo.png" alt="DMOOP" width={40} height={12} className="w-full h-auto object-contain" />
              </span>
              {renaming && conv ? (
                <input
                  autoFocus
                  value={renameValue}
                  onChange={(e) => setRenameValue(e.target.value)}
                  onBlur={commitRename}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") commitRename();
                    if (e.key === "Escape") setRenaming(false);
                  }}
                  className="text-[13px] font-medium bg-white border border-[var(--dmoop-accent)] rounded-md px-2 py-0.5 focus:outline-none w-60"
                />
              ) : (
                <span className="text-[13px] text-[var(--dmoop-text-secondary)] font-medium truncate">
                  {conv ? conv.title : current.label}
                </span>
              )}
            </div>
          </div>

          <div className="flex items-center gap-1 shrink-0">
            {/* Share */}
            <div ref={shareRef} className="relative">
              <button
                onClick={() => hasConv && setShareOpen((o) => !o)}
                disabled={!hasConv}
                className={cn(
                  "hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[13px] font-medium transition-all duration-200 active:scale-95",
                  hasConv
                    ? "text-[var(--dmoop-text-secondary)] hover:bg-white hover:shadow-[var(--dmoop-shadow-sm)] hover:text-[var(--dmoop-text-primary)]"
                    : "text-[var(--dmoop-text-tertiary)] cursor-not-allowed opacity-50"
                )}
              >
                <Share2 size={13} strokeWidth={2.2} /> Share
              </button>
              <button
                onClick={() => hasConv && setShareOpen((o) => !o)}
                disabled={!hasConv}
                className={cn(
                  "sm:hidden p-2 rounded-lg transition-all duration-200 active:scale-95",
                  hasConv
                    ? "text-[var(--dmoop-text-secondary)] hover:bg-white hover:shadow-[var(--dmoop-shadow-sm)]"
                    : "text-[var(--dmoop-text-tertiary)] cursor-not-allowed opacity-50"
                )}
              >
                <Share2 size={14} />
              </button>

              {shareOpen && conv && (
                <div
                  className="absolute right-0 top-full mt-1.5 w-[230px] rounded-xl overflow-hidden z-30 dmoop-scale-in"
                  style={{
                    background: "var(--dmoop-gradient-card)",
                    border: "1px solid var(--dmoop-border-soft)",
                    boxShadow: "var(--dmoop-shadow-xl)",
                  }}
                >
                  <div className="px-3.5 pt-3 pb-1.5">
                    <p className="text-[10px] font-semibold uppercase tracking-wider text-[var(--dmoop-text-tertiary)]">
                      Share conversation
                    </p>
                  </div>
                  <MenuButton onClick={copyAsMarkdown} icon={copiedShare ? Check : Copy} iconClass={copiedShare ? "text-emerald-600" : ""}>
                    {copiedShare ? "Copied to clipboard" : "Copy as markdown"}
                  </MenuButton>
                  <MenuButton onClick={downloadAsMarkdown} icon={Download}>
                    Download as .md
                  </MenuButton>
                  {typeof navigator !== "undefined" && "share" in navigator && (
                    <MenuButton onClick={nativeShare} icon={Share2}>
                      Share via…
                    </MenuButton>
                  )}
                </div>
              )}
            </div>

            {/* More */}
            <div ref={moreRef} className="relative">
              <button
                onClick={() => setMoreOpen((o) => !o)}
                className="p-2 rounded-lg text-[var(--dmoop-text-secondary)] transition-all duration-200 hover:bg-white hover:shadow-[var(--dmoop-shadow-sm)] active:scale-95"
              >
                <MoreHorizontal size={14} />
              </button>

              {moreOpen && (
                <div
                  className="absolute right-0 top-full mt-1.5 w-[220px] rounded-xl overflow-hidden z-30 dmoop-scale-in"
                  style={{
                    background: "var(--dmoop-gradient-card)",
                    border: "1px solid var(--dmoop-border-soft)",
                    boxShadow: "var(--dmoop-shadow-xl)",
                  }}
                >
                  {hasConv && (
                    <>
                      <MenuButton onClick={startRename} icon={Pencil}>
                        Rename conversation
                      </MenuButton>
                      <MenuButton onClick={downloadAsMarkdown} icon={Download}>
                        Export as .md
                      </MenuButton>
                      <div className="h-px bg-[var(--dmoop-border-soft)] mx-2" />
                    </>
                  )}
                  <MenuButton onClick={() => { setMoreOpen(false); showTour(); }} icon={HelpCircle}>
                    Show tour again
                  </MenuButton>
                  {hasConv && (
                    <>
                      <div className="h-px bg-[var(--dmoop-border-soft)] mx-2" />
                      <MenuButton onClick={deleteCurrent} icon={Trash2} danger>
                        Delete conversation
                      </MenuButton>
                    </>
                  )}
                </div>
              )}
            </div>
          </div>
        </header>

        {!conv || conv.messages.length === 0 ? (
          <WelcomeScreen />
        ) : (
          <MessageThread />
        )}

        <div className="shrink-0 relative z-10">
          <InputBar />
        </div>
      </main>
    </div>
  );
}

function MenuButton({
  onClick, icon: Icon, iconClass = "", danger = false, children,
}: {
  onClick: () => void;
  icon: React.ComponentType<{ size: number; className?: string }>;
  iconClass?: string;
  danger?: boolean;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      className={cn(
        "w-full flex items-center gap-2.5 px-3.5 py-2.5 text-[13px] font-medium transition-colors text-left",
        danger
          ? "text-red-600 hover:bg-red-50"
          : "text-[var(--dmoop-text-primary)] hover:bg-[#faf6ef]"
      )}
    >
      <Icon size={13} className={iconClass || (danger ? "text-red-500" : "text-[var(--dmoop-text-secondary)]")} />
      <span>{children}</span>
    </button>
  );
}
